### PR TITLE
PHP7

### PR DESCRIPTION
**Pull request by EtchReborn**
Php7 Compatile

### CODE REVIEW

**Comment by jasonwynn10** [comment]
That isn't how php works 🤦‍♂️

**Comment by EtchReborn** [comment]
Ik but can you make it php7

**Comment by jasonwynn10** [comment]
php 7 has backwards compatibility. it doesn't need changed

**Comment by EtchReborn** [comment]
Some Softwares doesent need a php binary so you need to make the plugin work with php7 or no one will be happy to use it (I tryed it and it dosent work :,(

**Comment by jasonwynn10** [comment]
The only way pocketmine works in the first place is with php binaries. You obviously don't fully understand what you are talking about.

**Comment by EtchReborn** [comment]
When i say some softwares i mean not pocketmine i mean Tesseract, Clearsky, Genisys, BlueLight etc I just hoped you could make it php7 sorry if i made you angry i just need this MobAI Because i dont like other kinds then this one

**Comment by jasonwynn10** [comment]
Each of those softwares require php!

**Comment by EtchReborn** [comment]
Okay sorry i just want a working mobai nothing else sorry for making you mad

**Pull request closed without merging**
